export const AppRoutes = {
  public: {
    home: '/',
    howItWorks: '/como-funciona',
    businesses: '/para-negocios',
    hazteDriver: '/hazte-driver',
    contact: '/contacto',
    portalLogin: '/portal/login',
  },
  portal: {
    root: '/portal',
    dashboard: '/portal/dashboard',
    orders: '/portal/orders',
    orderDetail: '/portal/orders/:id',
    menu: '/portal/menu',
    categories: '/portal/categories',
    products: '/portal/products',
    branchStatus: '/portal/branch-status',
    hours: '/portal/hours',
    staff: '/portal/staff',
    admin: {
      root: '/portal/admin',
      platformBusinesses: '/portal/admin/platform/businesses',
      platformBusinessDetail: '/portal/admin/platform/businesses/:merchantId',
      security: '/portal/admin/platform/security',
      payments: '/portal/admin/payments',
      turn: '/portal/admin/turn',
      commerce: '/portal/admin/commerce',
      branches: '/portal/admin/branches',
      localStatus: '/portal/admin/local-status',
      operationalMenu: '/portal/admin/operational-menu',
      branchNew: '/portal/admin/branches/new',
      branchDetail: '/portal/admin/branches/:branchId',
      staff: '/portal/admin/staff',
      customers: '/portal/admin/customers',
      customerDetail: '/portal/admin/customers/:customerId',
      drivers: '/portal/admin/drivers',
      driverDetail: '/portal/admin/drivers/:driverId',
      promotions: '/portal/admin/promotions',
      promotionDetail: '/portal/admin/promotions/:promotionId',
      messages: '/portal/admin/messages',
      messageDetail: '/portal/admin/messages/:conversationId',
      settlements: '/portal/admin/settlements',
      merchantSettlementDetail: '/portal/admin/settlements/merchant/:settlementId',
      driverSettlementDetail: '/portal/admin/settlements/driver/:settlementId',
      system: '/portal/admin/system',
      categories: '/portal/admin/catalog/categories',
      modifiers: '/portal/admin/catalog/modifiers',
      products: '/portal/admin/catalog/products',
      productNew: '/portal/admin/catalog/products/new',
      productDetail: '/portal/admin/catalog/products/:productId',
      orders: '/portal/admin/orders',
      orderDetail: '/portal/admin/orders/:orderId',
    },
  },
};
